In [71]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

def show(title, image):
    height = image.shape[0]
    width = image.shape[1]
    #image = cv2.resize(image, (width, height))
    image = cv2.resize(image, (int(width*0.4), int(height*0.4)))
    cv2.imshow(title, image)
def found(img):
    #red_channel = img[:,:,1]
    sum = np.count_nonzero(img == 255)
    all = np.size(img)
    
    print('hairpixels:',sum)
    print('imagepixels:',all,' should be: ', img.shape[0]*img.shape[1])
    print('percentage:', (sum/all)*100)
    
    return sum
def process(path):
    img = cv2.imread(path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    kernel = np.ones((3,3), np.uint8)
    edges = cv2.Canny(gray,40,200,kernel)
    
    #hmmm I dont like dilate and erosion. gives way to many hairs.
    #img_dilation = cv2.dilate(edges, kernel, iterations =1)
    #img_erosion = cv2.erode(img_dilation, kernel, iterations = 1)
    
    #show('original', img)
    #show('canny', edges)
    #show('dilation', img_dilation)
    #show('erode', img_erosion)
    #show('inversion', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return img, edges

In [96]:
def intensity(orig, edges):
    
    print('hi')
    binary = np.ones(img.shape[:2], dtype="uint8")
    binary[:,:] = (img != 0) # 0 or 1 depending on wehter it is ==0
    #where binary = 1 
    intensity = binary * orig
    show('intensity',intensity)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [97]:
def dectect(path):
    orig,img = process(path)
    found(img)
    intensity(img,img)
    return orig,img

In [98]:
orig,img = detect('HairTest1_18Hairs.png')

hairpixels: 104085
imagepixels: 5857280  should be:  5857280
percentage: 1.7770193673513988


In [80]:
orig,img = detect('Mummel_6_long.jpg')

hairpixels: 114670
imagepixels: 12192768  should be:  12192768
percentage: 0.9404755343495422


In [81]:
orig,img = detect('Mummel_12_long_dense.jpg')

hairpixels: 120673
imagepixels: 12192768  should be:  12192768
percentage: 0.98970963771311


In [82]:
orig,img = detect('Mummel_12_long_loose.jpg')

hairpixels: 154968
imagepixels: 12192768  should be:  12192768
percentage: 1.2709829302091207


In [83]:
orig,img = detect('Mummel_1.jpg')

hairpixels: 10539
imagepixels: 9204120  should be:  9204120
percentage: 0.11450307036414127


In [52]:
def diff(orig, img):
    h = orig.shape[0]
    w = orig.shape[1]
    #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.cvtColor(orig, cv2.COLOR_BGR2GRAY)
    res = orig.copy()
    thresh = np.ones(image_in.shape[:2], dtype="uint8") * 255
    thresh[:,:] = (img != 0) # 0 or 1 depending on wehter it is ==0
    res = 100+gray*0.2
    
    
    
    for y in range(0, h):
        for x in range(0, w):
            # threshold the pixel
            colors = orig[y,x]
            #print(img[y,x])
            if int(img[y,x]) == 0: # if black, no hair found.
                #lets make it a much lighter shade of the original
                res[y, x] = 100+gray[y,x]*0.2
            else:
                res[y,x] = [255,0,0]#colors-100 #ahir pixel will be 
    show('original', orig)
    show('diff', res)
    show('gray', gray)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [32]:
def diff(orig, img):
    h = orig.shape[0]
    w = orig.shape[1]
    #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.cvtColor(orig, cv2.COLOR_BGR2GRAY)
    res = orig.copy()
    thresh = np.ones(orig.shape[:2], dtype="uint8")
    thresh[:,:] = (img != 0) # 0 or 1 depending on wehter it is ==0

    print(gray)
    gray = 255+(gray*0.2)
    print(gray)
    res = (100+gray*0.2)*(thresh)
   
    found(img)
    
    
    show('gray', gray)
    show('res', res)
    show('original', orig)
    show('img', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
diff(orig, img)

[[161 160 157 ... 164 159 160]
 [158 161 158 ... 163 158 161]
 [156 160 158 ... 163 158 162]
 ...
 [186 184 185 ... 128 130 129]
 [188 186 186 ... 130 132 128]
 [187 186 187 ... 132 134 126]]
[[287.2 287.  286.4 ... 287.8 286.8 287. ]
 [286.6 287.2 286.6 ... 287.6 286.6 287.2]
 [286.2 287.  286.6 ... 287.6 286.6 287.4]
 ...
 [292.2 291.8 292.  ... 280.6 281.  280.8]
 [292.6 292.2 292.2 ... 281.  281.4 280.6]
 [292.4 292.2 292.4 ... 281.4 281.8 280.2]]
104085


In [53]:
diff(orig,img)

In [10]:
detect('blonde on black-1.png')

In [31]:
detect('very large hair bunch.jpg')

In [25]:

cpdef unsigned char[:, :] threshold_fast(int T, unsigned char [:, :] image):
    # set the variable extension types
    cdef int x, y, w, h
    
    # grab the image dimensions
    h = image.shape[0]
    w = image.shape[1]
    
    # loop over the image
    for y in range(0, h):
        for x in range(0, w):
            # threshold the pixel
            image[y, x] = 255 if image[y, x] >= T else 0
    
    # return the thresholded image
    return image

SyntaxError: invalid syntax (<ipython-input-25-71a28675c926>, line 1)

In [17]:
import cython

ModuleNotFoundError: No module named 'cython'

In [11]:
print(orig)

[[[159 158 167]
  [158 157 166]
  [155 154 163]
  ...
  [162 161 170]
  [157 156 165]
  [158 157 166]]

 [[156 155 164]
  [159 158 167]
  [156 155 164]
  ...
  [161 160 169]
  [156 155 164]
  [159 158 167]]

 [[154 153 162]
  [158 157 166]
  [156 155 164]
  ...
  [161 160 169]
  [156 155 164]
  [160 159 168]]

 ...

 [[179 188 185]
  [177 186 183]
  [178 187 184]
  ...
  [110 131 129]
  [112 133 131]
  [111 132 130]]

 [[181 190 187]
  [179 188 185]
  [179 188 185]
  ...
  [112 133 131]
  [114 135 133]
  [110 131 129]]

 [[180 189 186]
  [179 188 185]
  [180 189 186]
  ...
  [114 135 133]
  [116 137 135]
  [108 129 127]]]


In [23]:
def do_things(a):
    print(a ,"end")
    return a

In [24]:
import numpy as np
example = orig
def fast():
     img = example.copy()
     height, width, depth = img.shape
     do_things(img[0:height, 0:width])
        # DO THIS INSTEAD
     return img 
fast()

[[[159 158 167]
  [158 157 166]
  [155 154 163]
  ...
  [162 161 170]
  [157 156 165]
  [158 157 166]]

 [[156 155 164]
  [159 158 167]
  [156 155 164]
  ...
  [161 160 169]
  [156 155 164]
  [159 158 167]]

 [[154 153 162]
  [158 157 166]
  [156 155 164]
  ...
  [161 160 169]
  [156 155 164]
  [160 159 168]]

 ...

 [[179 188 185]
  [177 186 183]
  [178 187 184]
  ...
  [110 131 129]
  [112 133 131]
  [111 132 130]]

 [[181 190 187]
  [179 188 185]
  [179 188 185]
  ...
  [112 133 131]
  [114 135 133]
  [110 131 129]]

 [[180 189 186]
  [179 188 185]
  [180 189 186]
  ...
  [114 135 133]
  [116 137 135]
  [108 129 127]]] end


array([[[159, 158, 167],
        [158, 157, 166],
        [155, 154, 163],
        ...,
        [162, 161, 170],
        [157, 156, 165],
        [158, 157, 166]],

       [[156, 155, 164],
        [159, 158, 167],
        [156, 155, 164],
        ...,
        [161, 160, 169],
        [156, 155, 164],
        [159, 158, 167]],

       [[154, 153, 162],
        [158, 157, 166],
        [156, 155, 164],
        ...,
        [161, 160, 169],
        [156, 155, 164],
        [160, 159, 168]],

       ...,

       [[179, 188, 185],
        [177, 186, 183],
        [178, 187, 184],
        ...,
        [110, 131, 129],
        [112, 133, 131],
        [111, 132, 130]],

       [[181, 190, 187],
        [179, 188, 185],
        [179, 188, 185],
        ...,
        [112, 133, 131],
        [114, 135, 133],
        [110, 131, 129]],

       [[180, 189, 186],
        [179, 188, 185],
        [180, 189, 186],
        ...,
        [114, 135, 133],
        [116, 137, 135],
        [108, 129, 127]]

In [3]:
def slow():
     img = example.copy()
     height, width, depth = img.shape
     for i in range(0, height):             #looping at python speed...
         for j in range(0, (width//4)):     #...
             for k in range(0,depth):       #...
                 img[i,j,k] = 0
     return img
slow()

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 

In [103]:
newhigh = 255
oldhigh = 200
newlow = oldlow = 40
intensity = 0
print(newlow + ((newhigh - newlow) / (oldhigh - oldlow)) * (intensity -oldlow))

-13.75


In [8]:
import numpy as np
a = np.array([0,1,5,3,4])
a2 = a[1::2]
a2

array([1, 3])